#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jellyfin"
name = "Jellyfin"
description.en = "Media System that manage and stream your media"
description.fr = "Système multimédia qui gère et diffuse vos médias"

version = "12.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-2.0-only"
website = "https://jellyfin.org"
demo = "https://demo.jellyfin.org/stable/web/index.html"
userdoc = "https://jellyfin.org/docs/"
code = "https://github.com/jellyfin/jellyfin"
cpe = "cpe:2.3:a:jellyfin:jellyfin"
fund = "https://opencollective.com/jellyfin"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["arm64", "amd64"]
multi_instance = true

ldap = true

sso = true

disk = "300M"
ram.build = "200M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jellyfin"

    [install.init_main_permission]
    help.en = "Jellyfin has its own login system, you should make it public to let external clients access it (mobile app, etc.)."
    help.fr = "Jellyfin a son propre système de connexion, vous devriez la laisser publique pour permettre la connexion de clients externes (app mobile, etc.)."
    type = "group"
    default = "visitors"

    [install.init_admin_permission]
    ask.en = "Select an account to grant it access to Jellyfin's administration panel."
    ask.fr = "Choisissez un compte pour lui accorder l'accès au tableau de bord d'administration de Jellyfin."
    help.en = "You can grant this access to other accounts and groups with the permission system later."
    help.fr = "Vous pourrez octroire l'accès à d'autres comptes et groupes avec le système de permissions plus tard."
    type = "user"

[resources]

    [resources.sources.main]
    arm64.url = "https://repo.jellyfin.org/files/server/linux/stable/v12.0/arm64/jellyfin_12.0-arm64.tar.xz"
    arm64.sha256 = "f2e6926d4ff85382d2d1de255796aaae60f56fedaea5aaecf0d183ae5083d2a7"
    amd64.url = "https://repo.jellyfin.org/files/server/linux/stable/v12.0/amd64/jellyfin_12.0-amd64.tar.xz"
    amd64.sha256 = "13c52b18119e5c2e9a2682f7b97eb4fac9babd64d43618c4ce567e578e80124a"

    format = "tar.xz"
    extract = true
    in_subdir = true
    prefetch = false

    [resources.sources.main_archive]
    arm64.url = "https://repo.jellyfin.org/archive/server/linux/stable/v12.0/arm64/jellyfin_12.0-arm64.tar.xz"
    arm64.sha256 = "f2e6926d4ff85382d2d1de255796aaae60f56fedaea5aaecf0d183ae5083d2a7"
    amd64.url = "https://repo.jellyfin.org/archive/server/linux/stable/v12.0/amd64/jellyfin_12.0-amd64.tar.xz"
    amd64.sha256 = "13c52b18119e5c2e9a2682f7b97eb4fac9babd64d43618c4ce567e578e80124a"

    format = "tar.xz"
    extract = true
    in_subdir = true
    prefetch = false

    [resources.sources.ffmpeg]
    arm64.url = "https://repo.jellyfin.org/files/ffmpeg/linux/8.x/8.1.2-4/arm64/jellyfin-ffmpeg_8.1.2-4_portable_linuxarm64-gpl.tar.xz"
    arm64.sha256 = "ceb9642ee513491d0440bc0027dfa33f2fc6c9966cabb0ec69f43edcbb853e84"
    amd64.url = "https://repo.jellyfin.org/files/ffmpeg/linux/8.x/8.1.2-4/amd64/jellyfin-ffmpeg_8.1.2-4_portable_linux64-gpl.tar.xz"
    amd64.sha256 = "6e7150c358f9817a04ce82c62d81135cb4535d8525047393f4b296fff3d7a664"

    format = "tar.xz"
    extract = true
    in_subdir = false

    [resources.sources.plugin_ldap]
    url = "https://repo.jellyfin.org/files/plugin/ldap-authentication/ldap-authentication_24.0.0.0.zip"
    sha256 = "3be1f9d6a6ce9ea375e556dd30136d178a8dbe35cbe866d30d3451dc3ff7e804"
    in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    # auth_header=false is because Jellyfin expects custom data in the Authorization HTTP header (notably, for Jellyfin Vue)
    main.url = "/"
    main.auth_header = false

    admin.protected = true
    admin.auth_header = false
    admin.show_tile = false

    [resources.ports]
    main.default = 8095
    # If one day we plan to declare them
    #servicediscovery.default = 1900
    #servicediscovery.exposed = "UDP"
    #servicediscovery.fixed = true
    #clientdiscovery.default = 7359
    #clientdiscovery.exposed = "UDP"
    #clientdiscovery.fixed = true

    [resources.apt]
    packages = [
        "sqlite3" # temporarily needed to tweak db during upgrade script to 10.11.5
    ]
