## The default `client_max_body_size` is 1M, this might not be enough for some posters, etc.
client_max_body_size 20M;

# Security / XSS Mitigation Headers
more_set_headers "X-Content-Type-Options: nosniff";

# Permissions policy. May cause issues with some clients
more_set_headers "Permissions-Policy: accelerometer=(), ambient-light-sensor=(), battery=(), bluetooth=(), camera=(), clipboard-read=(), display-capture=(), document-domain=(), encrypted-media=(), gamepad=(), geolocation=(), gyroscope=(), hid=(), idle-detection=(), interest-cohort=(), keyboard-map=(), local-fonts=(), magnetometer=(), microphone=(), payment=(), publickey-credentials-get=(), serial=(), sync-xhr=(), usb=(), xr-spatial-tracking=()" always;

# Content Security Policy
# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
# Enforces https content and restricts JS/CSS to origin
# External Javascript (such as cast_sender.js for Chromecast) must be whitelisted.
more_set_headers "Content-Security-Policy: default-src https: data: blob: ; img-src 'self' https://* ; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://www.gstatic.com https://www.youtube.com blob:; worker-src 'self' blob:; connect-src 'self'; object-src 'none'; font-src 'self'" always;

#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {
    # Proxy main Jellyfin traffic
    proxy_pass http://127.0.0.1:__PORT____PATH__/;

    include proxy_params_with_auth;
    proxy_set_header X-Forwarded-Protocol $scheme;

    # Disable buffering when the nginx proxy gets very resource heavy upon streaming
    proxy_buffering off;
}

location __PATH__/socket {
    # Proxy Jellyfin Websockets traffic
    proxy_pass http://127.0.0.1:__PORT____PATH__;

    include proxy_params_with_auth;
    proxy_set_header X-Forwarded-Protocol $scheme;
}
