#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --timeout=15

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# BASE URL
#=================================================

# Change the path in system.xml config file
if [ $change_path -eq 1 ]; then
	# If somehow <BaseUrl /> was not replaced during install
	if grep -q "<BaseUrl />" "$config_path/network.xml"; then
		ynh_replace --match="<BaseUrl />" --replace="<BaseUrl>$new_path</BaseUrl>" --file="$config_path/network.xml"
	else
		ynh_replace --match="<BaseUrl>$old_path</BaseUrl>" --replace="<BaseUrl>$new_path</BaseUrl>" --file="$config_path/network.xml"
	fi
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --timeout=15

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
