#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RECREATE THE DEDICATED USER
#=================================================
ynh_script_progression "Reconfiguring the dedicated system user..."

# It could be created later by the deb, but it's cleaner here
if getent group render && ! id -Gn "$app" | grep -qw "\brender\b" >/dev/null; then
	# Add user to render group
	adduser $app render
fi

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$data_path"
ynh_restore "$config_path"
ynh_restore "/etc/default/jellyfin" || true

#=================================================
# REINSTALL PACKAGES
#=================================================
ynh_script_progression "Reinstalling packages..."

#ynh_systemctl --service="$app" --action="mask"
install_jellyfin_packages
#ynh_systemctl --service="$app" --action="unmask"

#=================================================
# RESTORE USER RIGHTS
#=================================================
ynh_script_progression "Restoring user rights..."

# Restore permissions on app files
chown -R "$app:" "$data_path"
chown -R "$app:" "$config_path"

#=================================================
# YUNOHOST MULTIMEDIA INTEGRATION
#=================================================
ynh_script_progression "Adding multimedia directories..."

# Build YunoHost multimedia directories
ynh_multimedia_build_main_dir

# Allow Jellyfin to write into these directories
ynh_multimedia_addaccess "$app"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/jellyfin.service.d" || true
systemctl enable jellyfin.service --quiet
yunohost service add "$app" --description="Jellyfin media center"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --timeout=15

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
